[project]
name = "lambda-layer"
version = "0.1.0"
description = "Shared Lambda layer: Powertools (Log, Metrics)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aws-lambda-powertools>=2.36.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []
